encoding: utf-8

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "HTML, CSS, JS"
author: "var-bin"
email: "var.bin.com@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  "Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://var-bin.com" # the base hostname & protocol for your site
host: "localhost"
port: 4000
twitter_username: "var_bincom"
github_username:  "var-bin"
exclude: ["bower_components", "node_modules", "gulpfile.js", "package.json", "*.sublime-*"]

# Build settings
markdown: "kramdown"

# includes
head: "head.html"
header: "header.html"
footer: "footer.html"
social: "social.html"

# sass
sass:
  sass_dir: _sass
  style: compressed
# permalinks
permalink: /:categories/:title/
